# Generated by Django 5.2.12 on 2026-03-31 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_teacher_qualification'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='classes',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
