# Generated by Django 5.2.12 on 2026-04-02 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_schoolclass_subject"),
    ]

    operations = [
        migrations.RenameField(
            model_name="student",
            old_name="parent",
            new_name="user_account",
        ),
    ]
