# Generated by Django 5.2.12 on 2026-04-02 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_rename_parent_student_user_account"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomeworkFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("done", "Done"),
                            ("not_done", "Not Done"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("message", models.TextField(blank=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "homework",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedbacks",
                        to="core.homework",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.student"
                    ),
                ),
            ],
            options={
                "ordering": ["student__roll_number", "student__name"],
            },
        ),
        migrations.AddConstraint(
            model_name="homeworkfeedback",
            constraint=models.UniqueConstraint(
                fields=("homework", "student"),
                name="unique_homework_feedback_per_student",
            ),
        ),
    ]
