# Generated by Django 5.2.12 on 2026-04-02 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_homeworkfeedback"),
    ]

    operations = [
        migrations.CreateModel(
            name="TimetableEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("class_name", models.CharField(max_length=20)),
                (
                    "day",
                    models.CharField(
                        choices=[
                            ("Monday", "Monday"),
                            ("Tuesday", "Tuesday"),
                            ("Wednesday", "Wednesday"),
                            ("Thursday", "Thursday"),
                            ("Friday", "Friday"),
                            ("Saturday", "Saturday"),
                        ],
                        max_length=10,
                    ),
                ),
                ("lecture_number", models.PositiveSmallIntegerField()),
                ("subject", models.CharField(max_length=50)),
            ],
            options={
                "ordering": ["class_name", "day", "lecture_number"],
            },
        ),
        migrations.AddConstraint(
            model_name="timetableentry",
            constraint=models.UniqueConstraint(
                fields=("class_name", "day", "lecture_number"),
                name="unique_timetable_slot_per_class",
            ),
        ),
    ]
