# Generated by Django 5.2.12 on 2026-04-02 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_timetableentry"),
    ]

    operations = [
        migrations.AddField(
            model_name="homeworkfeedback",
            name="teacher_read",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="homeworkfeedback",
            name="teacher_read_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
