# Generated by Django 5.2.12 on 2026-04-03 00:00

from datetime import date
from django.db import migrations, models


def create_fee_records(apps, schema_editor):
    Student = apps.get_model("core", "Student")
    StudentFee = apps.get_model("core", "StudentFee")
    current_year = date.today().year

    for student in Student.objects.all():
        for month in range(1, 13):
            StudentFee.objects.get_or_create(
                student=student,
                year=current_year,
                month=month,
                defaults={
                    "amount": student.monthly_fee,
                    "due_date": date(current_year, month, 7),
                },
            )


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_notificationread"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="monthly_fee",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="StudentFee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveIntegerField()),
                ("month", models.PositiveSmallIntegerField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("due_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[("unpaid", "Unpaid"), ("paid", "Paid")],
                        default="unpaid",
                        max_length=10,
                    ),
                ),
                ("paid_date", models.DateField(blank=True, null=True)),
                ("receipt_number", models.CharField(blank=True, max_length=50)),
                ("remarks", models.CharField(blank=True, max_length=200)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=models.deletion.CASCADE,
                        related_name="fees",
                        to="core.student",
                    ),
                ),
            ],
            options={
                "ordering": ["-year", "-month"],
            },
        ),
        migrations.AddConstraint(
            model_name="studentfee",
            constraint=models.UniqueConstraint(
                fields=("student", "year", "month"),
                name="unique_fee_record_per_student_month",
            ),
        ),
        migrations.RunPython(create_fee_records, migrations.RunPython.noop),
    ]
