# Generated by Django 5.2.12 on 2026-04-03 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_student_monthly_fee_studentfee"),
    ]

    operations = [
        migrations.CreateModel(
            name="SchoolClassSubject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "school_class",
                    models.ForeignKey(
                        on_delete=models.deletion.CASCADE,
                        related_name="class_subjects",
                        to="core.schoolclass",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=models.deletion.CASCADE,
                        to="core.subject",
                    ),
                ),
            ],
            options={
                "ordering": ["school_class__name", "subject__name"],
            },
        ),
        migrations.AddConstraint(
            model_name="schoolclasssubject",
            constraint=models.UniqueConstraint(
                fields=("school_class", "subject"),
                name="unique_subject_per_school_class",
            ),
        ),
    ]
