# Generated by Django 5.2.12 on 2026-04-04 00:00

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_schoolclasssubject"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdmissionApplication",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("campus", models.CharField(choices=[("Girls Campus", "Girls Campus"), ("Kids Campus", "Kids Campus"), ("Rustam Park Campus", "Rustam Park Campus")], max_length=30)),
                ("class_applying_for", models.CharField(max_length=30)),
                ("student_name", models.CharField(max_length=120)),
                ("gender", models.CharField(max_length=10)),
                ("date_of_birth", models.DateField()),
                ("b_form_number", models.CharField(blank=True, max_length=30)),
                ("previous_school", models.CharField(blank=True, max_length=120)),
                ("religion", models.CharField(blank=True, max_length=50)),
                ("guardian_name", models.CharField(max_length=120)),
                ("relationship", models.CharField(max_length=40)),
                ("cnic_number", models.CharField(max_length=30)),
                ("occupation", models.CharField(blank=True, max_length=100)),
                ("phone", models.CharField(max_length=30)),
                ("whatsapp", models.CharField(blank=True, max_length=30)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("emergency_contact", models.CharField(blank=True, max_length=30)),
                ("address", models.TextField()),
                ("city", models.CharField(max_length=80)),
                ("message", models.TextField(blank=True)),
                ("transport_required", models.CharField(blank=True, max_length=10)),
                ("student_photo", models.FileField(blank=True, upload_to=core.models.admission_upload_path)),
                ("birth_certificate", models.FileField(blank=True, upload_to=core.models.admission_upload_path)),
                ("guardian_cnic", models.FileField(blank=True, upload_to=core.models.admission_upload_path)),
                ("previous_result", models.FileField(blank=True, upload_to=core.models.admission_upload_path)),
                ("transfer_certificate", models.FileField(blank=True, upload_to=core.models.admission_upload_path)),
                ("additional_document", models.FileField(blank=True, upload_to=core.models.admission_upload_path)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("email_sent", models.BooleanField(default=False)),
            ],
            options={"ordering": ["-submitted_at"]},
        ),
    ]
