# Generated by Django 5.2.12 on 2026-04-06 07:36

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_admissionapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campus', models.CharField(choices=[('Girls Campus', 'Girls Campus'), ('Kids Campus', 'Kids Campus'), ('Rustam Park Campus', 'Rustam Park Campus')], max_length=30)),
                ('full_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('position_applied_for', models.CharField(max_length=120)),
                ('highest_qualification', models.CharField(max_length=120)),
                ('years_of_experience', models.CharField(blank=True, max_length=30)),
                ('cover_letter', models.TextField(blank=True)),
                ('cv_file', models.FileField(upload_to=core.models.career_upload_path)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('email_sent', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
