# Generated by Django 5.2.12 on 2026-04-26 08:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_careerapplication_more_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent')], default='present', max_length=10)),
                ('remarks', models.CharField(blank=True, max_length=200)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='core.teacher')),
            ],
            options={
                'ordering': ['-date', 'teacher__user__first_name', 'teacher__user__username'],
                'constraints': [models.UniqueConstraint(fields=('teacher', 'date'), name='unique_teacher_attendance_per_day')],
            },
        ),
    ]
