# Generated by Django 5.2.12 on 2026-05-03 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_studentfee_paid_amount_alter_studentfee_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherattendance',
            name='entry_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacherattendance',
            name='exit_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
