# Generated by Django 5.2.12 on 2026-05-03 12:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_teacherattendance_entry_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolTimingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Current School Timing', max_length=80)),
                ('school_start_time', models.TimeField(default=datetime.time(7, 0))),
                ('late_after_time', models.TimeField(default=datetime.time(7, 15))),
                ('leave_before_time', models.TimeField(default=datetime.time(13, 0))),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'School Timing',
                'verbose_name_plural': 'School Timings',
            },
        ),
    ]
