# Generated by Django 5.2.12 on 2026-05-03 12:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_schooltimingsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='schooltimingsettings',
            name='school_end_time',
            field=models.TimeField(default=datetime.time(13, 30)),
        ),
    ]
