# Generated by Django 5.2.12 on 2026-05-04 20:07

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_teacheryearlyremark'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='campus',
            field=models.CharField(choices=[('Girls Campus', 'Girls Campus'), ('Kids Campus', 'Kids Campus'), ('Rustam Park Campus', 'Rustam Park Campus')], default='Girls Campus', max_length=30),
        ),
        migrations.AddField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='id_card_valid_until',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='student_photo',
            field=models.FileField(blank=True, null=True, upload_to=core.models.student_id_photo_upload_path),
        ),
    ]
