# Generated by Django 5.2.12 on 2026-05-05 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_student_campus_student_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='target_classes',
            field=models.ManyToManyField(blank=True, related_name='notifications', to='core.schoolclass'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='audience',
            field=models.CharField(choices=[('all', 'All'), ('students', 'Students'), ('staff', 'Staff'), ('classwise', 'Class Wise')], default='all', max_length=12),
        ),
    ]
